# Generated by Django 5.2.1 on 2025-06-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('rating', models.FloatField(db_index=True)),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['category'], name='products_categor_fce6e6_idx'), models.Index(fields=['price'], name='products_price_fe467e_idx'), models.Index(fields=['rating'], name='products_rating_53cb37_idx'), models.Index(fields=['category', 'price'], name='products_categor_5d9235_idx')],
                'constraints': [models.CheckConstraint(check=models.Q(('price__gte', 0)), name='price_non_negative'), models.CheckConstraint(check=models.Q(('stock__gte', 0)), name='stock_non_negative'), models.CheckConstraint(check=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='rating_range_valid')],
            },
        ),
    ]
