# Generated by Django 3.2.25 on 2025-07-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('price', models.IntegerField(blank=True)),
                ('stock', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('rating', models.FloatField(blank=True)),
            ],
        ),
    ]
