# Generated by Django 3.2.25 on 2025-07-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_test2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
