# Generated by Django 3.2.25 on 2025-07-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_test2_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='test2',
            name='name2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='test2',
            name='price2',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test2',
            name='price',
            field=models.FloatField(blank=True, db_index=True),
        ),
    ]
