# Generated by Django 3.2.25 on 2025-07-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20250704_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test2',
            new_name='Product2',
        ),
    ]
